filter_settings.macaroni_filter_image:
  type: filter
  label: 'Filter to scale images'
  mapping:
    image_locations:
      type: mapping
      label: 'image_locations'
      mapping:
        local:
          type: boolean
          label: 'Allow local images.'
        remote:
          type: boolean
          label: 'Allow remote images.'
